[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wagtail-bucketav"
authors = [
    {name = "Jake Howard", email = "jake.howard@torchbox.com"},
    {name = "Nick Morton", email = "nick.moreton@torchbox.com"},
    {name = "Joshua Munn", email = "joshua.munn@torchbox.com"},
    {name = "Andy Babic", email = "andy.babic@torchbox.com"}
]
description = ""
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Wagtail",
    "Framework :: Wagtail :: 2",
    "Framework :: Wagtail :: 3"
]
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "Django>=3.0,<4.1",
    "Wagtail>=2.14,<4.0",
]

[project.optional-dependencies]
lint = [
    "black==22.6.0",
    "isort==5.10.1",
    "flake8==3.9.2",
]
test = [
    "pytest-cov==3.0.0",
    "pytest-mock==3.8.2",
    "pytest-django==4.5.2",
    "pytest==7.1.2",
]
documentation = [
    "mkdocs==1.1.2",
    "mkdocs-material==6.2.8",
    "mkdocs-mermaid2-plugin==0.5.1",
    "mkdocstrings==0.14.0",
    "mkdocs-include-markdown-plugin==2.8.0",
    "pygments==2.11.2"
]

[project.urls]
Home = "https://github.com/torchbox/wagtail-bucketav"
Source = "https://github.com/torchbox/wagtail-bucketav"

[tool.flit.module]
name = "wagtail_bucketav"

[tool.flit.sdist]
exclude = [
    "wagtail_bucketav/static_src",
    "wagtail_bucketav/tests",
    "wagtail_bucketav/testapp",
    "wagtail_bucketav/static/.gitignore",
    "docs",
    "*.js",
    "*.json",
    "*.ini",
    "*.yml",
    ".editorconfig"
]
include = [
    "wagtail_bucketav/static"
]

[tool.isort]
known_first_party = "wagtail_bucketav"
profile = "black"
skip = "migrations,node_modules,venv"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"

[tool.black]
line_length = 88
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | __pycache__
    | _build
    | build
    | dist
    | docs
    | venv
    | node_modules
  )/
)
'''
