name: "Test"

on: push

# Our test suite should cover:
# - Compatibility with the most recent versions of Django

jobs:
  lint:
    name: 🧹 Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[lint]
      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 django_bucketav --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 django_bucketav --count --exit-zero --max-complexity=10 --statistics
      - name: Run isort
        run: isort . --check-only --diff
      - name: Run black
        run: black . --check --fast

  test:
    name: 🧪 Test Python
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Django 5.x supports Python 3.10, 3.11, and 3.12
          # https://docs.djangoproject.com/en/5.0/releases/5.0/#python-compatibility
          - django-version: "Django>=5.0,<5.1"
            python-version: "3.12"
            latest: true
          - django-version: "Django>=5.0,<5.1"
            python-version: "3.11"
          - django-version: "Django>=5.0,<5.1"
            python-version: "3.10"
          # Django 4.2 supports Python 3.8, 3.9, 3.10, 3.11, and 3.12
          # https://docs.djangoproject.com/en/4.2/releases/4.2/#python-compatibility
          - django-version: "Django>=4.2,<5.0"
            python-version: "3.12"
          - django-version: "Django>=4.2,<5.0"
            python-version: "3.11"
          - django-version: "Django>=4.2,<5.0"
            python-version: "3.10"
          - django-version: "Django>=4.2,<5.0"
            python-version: "3.9"
          - django-version: "Django>=4.2,<5.0"
            python-version: "3.8"
          # Django 3.2 supports Python 3.8, 3.9, and 3.10
          # https://docs.djangoproject.com/en/3.2/releases/3.2/#python-compatibility
          - django-version: "Django>=3.2,<4.0"
            python-version: "3.10"
          - django-version: "Django>=3.2,<4.0"
            python-version: "3.9"
          - django-version: "Django>=3.2,<4.0"
            python-version: "3.8"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ matrix.name }}
          restore-keys: ${{ runner.os }}-pip-
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django-version }}"
      - if: ${{ !matrix.latest }}
        run: pytest
      - if: ${{ matrix.latest }}
        run: pytest --junitxml=junit/test-results.xml --cov=django_bucketav
      - if: ${{ matrix.latest }}
        uses: codecov/codecov-action@v1
        with:
          name: Python 3.8
