name: "Test bleeding edges"

on:
  push:
    branches: [main, "compat/django**", "compat/wagtail**"]
  schedule:
    # Run at 4pm every Monday, Wednesday and Friday
    - cron: "0 16 * * 0,2,4"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install git+https://github.com/wagtail/wagtail.git@main#egg=wagtail
      - name: "Test against Wagtail main"
        run: pytest
      - run: pip install git+https://github.com/django/django.git@main#egg=Django
      - name: "Test against Django main"
        run: pytest
