name: "Test"

on: push

# Our test suite should cover:
# - Compatibility with the most recent versions of Wagtail and Django
# - Compatibility with each version of Wagtail we support, changing the Django version where possible for some additional reassurance of Django compatibility

jobs:
  lint:
    name: 🧹 Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[lint]
      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run isort
        run: isort . --check-only --diff
      - name: Run black
        run: black . --check --fast

  test:
    name: 🧪 Test Python
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - wagtail-version: "Wagtail>=3.0,<4.0"
            django-version: "Django>=4.0,<5.0"
            python-version: 3.9
            latest: true
          - wagtail-version: "Wagtail>=2.16,<3.0"
            django-version: "Django>=3.2,<4.0"
            python-version: 3.9
          - wagtail-version: "Wagtail>=2.15,<2.16"
            django-version: "Django>=3.1,<3.2"
            python-version: 3.8
          - wagtail-version: "Wagtail>=2.14,<2.15"
            django-version: "Django>=3.0,<3.1"
            python-version: 3.7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ matrix.name }}
          restore-keys: ${{ runner.os }}-pip-
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.wagtail-version }}"
          pip install "${{ matrix.django-version }}"
      - if: ${{ !matrix.latest }}
        run: pytest
      - if: ${{ matrix.latest }}
        run: pytest --junitxml=junit/test-results.xml --cov=wagtail_bucketav
      - if: ${{ matrix.latest }}
        uses: codecov/codecov-action@v1
        with:
          name: Python 3.9
